In [2]:
import numpy as np
import pandas as pd

arr = np.arange(10)
print(type(arr))
s1 = pd.Series(arr)
print(s1)
print(type(s1))

arr2 = np.arange(12).reshape(4, 3)
print(arr2)
print(type(arr2))

<class 'numpy.ndarray'>
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32
<class 'pandas.core.series.Series'>
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
<class 'numpy.ndarray'>


In [3]:
df1 = pd.DataFrame(arr2)
print(df1)
print(type(df1))

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11
<class 'pandas.core.frame.DataFrame'>


In [4]:
dic2 = {'a':[1,2,3,4],'b':[5,6,7,8],'c':[9,10,11,12],'d':[13,14,15,16]}
print(dic2)
print(type(dic2))

{'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8], 'c': [9, 10, 11, 12], 'd': [13, 14, 15, 16]}
<class 'dict'>


In [5]:
df2 = pd.DataFrame(dic2)
print(df2)
print(type(df2))

   a  b   c   d
0  1  5   9  13
1  2  6  10  14
2  3  7  11  15
3  4  8  12  16
<class 'pandas.core.frame.DataFrame'>


In [6]:
dic3 = {'one':{'a':1,'b':2,'c':3,'d':4},'two':{'a':5,'b':6,'c':7,'d':8},'three':{'a':9,'b':10,'c':11,'d':12}}
print(dic3)
print(type(dic3))

{'one': {'a': 1, 'b': 2, 'c': 3, 'd': 4}, 'two': {'a': 5, 'b': 6, 'c': 7, 'd': 8}, 'three': {'a': 9, 'b': 10, 'c': 11, 'd': 12}}
<class 'dict'>


In [7]:
df3 = pd.DataFrame(dic3)
print(df3)
print(type(df3))

   one  three  two
a    1      9    5
b    2     10    6
c    3     11    7
d    4     12    8
<class 'pandas.core.frame.DataFrame'>


In [9]:
df4 = df3[['one', 'three']]
print(df4)
print(type(df4))

   one  three
a    1      9
b    2     10
c    3     11
d    4     12
<class 'pandas.core.frame.DataFrame'>


In [12]:
s3 = df3['one']
print(s3)
print(type(s3))

a    1
b    2
c    3
d    4
Name: one, dtype: int64
<class 'pandas.core.series.Series'>
