### numpy的速度要比纯python要快

In [1]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

[     0      1      2 ..., 999997 999998 999999]


In [2]:
%time for _ in range(10):my_arr2 = my_arr * 2

Wall time: 35.9 ms


In [4]:
%time for _ in range(10):my_list2 = [x * 2 for x in my_list]

Wall time: 1.16 s


### numpy的ndarry：一种多维数组对象

In [7]:
import numpy as np

data = np.random.randn(2, 3)# 生成（2,3）随机数组
print(data)

[[ 1.25298716 -1.7343435  -0.00697016]
 [-0.52350676 -0.67632315  0.72901536]]


In [11]:
print('data * 10: \n', data * 10)# 数学运算
print('data + data: \n', data + data)# 和自身相加

data * 10: 
 [[ 12.52987164 -17.34343498  -0.06970156]
 [ -5.23506758  -6.76323147   7.29015358]]
data + data: 
 [[ 2.50597433 -3.468687   -0.01394031]
 [-1.04701352 -1.35264629  1.45803072]]


In [12]:
print('data shape:', data.shape)
print('data dtype:', data.dtype)

data shape: (2, 3)
data dtype: float64


In [24]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)# 生成ndarray
print(data1)

[6, 7.5, 8, 0, 1]


In [28]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print('arr2:',arr2)
print('arr2.ndim',arr2.ndim)
print('arr2.shape',arr2.shape)

arr2: [[1 2 3 4]
 [5 6 7 8]]
arr2.ndim 2
arr2.shape (2, 4)


In [43]:
print(np.zeros(10))
print(np.zeros((3, 6)))
print(np.empty((2, 3, 2)))# 用empty是一对未初始化垃圾值

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[[  1.61272725e-312   0.00000000e+000]
  [  3.62633684e+228   8.82087105e+199]
  [  6.79000872e+180   2.09473745e-110]]

 [[  8.29655075e-114   1.09936966e+248]
  [  2.09666503e-110   6.48224638e+170]
  [  3.67145870e+228   1.16263363e+295]]]


In [44]:
print(np.arange(15))# arange是range数组版

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [45]:
arr1 = np.array([1, 2, 3], dtype=np.float64)# 转换时指定dtype类型
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [48]:
arr = np.array([1, 2, 3,  4, 5])
print(arr.dtype)

float_arr = arr.astype(np.float64)# 转换dtype类型
print(float_arr)

int32
[ 1.  2.  3.  4.  5.]


In [50]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(int_array.astype(calibers.dtype))# 根据已知dtype转换

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [52]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

print(arr > arr2)# 比较结果返回布尔值数组

[[ True False  True]
 [False  True False]]


In [53]:
# 广播性质
import numpy as np
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
print ('第一个数组：')  
print (a) 
print ('\n第二个数组：')  
print (b) 
print ('\n第一个数组加第二个数组：')  
print (a + b)

第一个数组：
[[  0.   0.   0.]
 [ 10.  10.  10.]
 [ 20.  20.  20.]
 [ 30.  30.  30.]]

第二个数组：
[ 1.  2.  3.]

第一个数组加第二个数组：
[[  1.   2.   3.]
 [ 11.  12.  13.]
 [ 21.  22.  23.]
 [ 31.  32.  33.]]


In [2]:
import numpy as np

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.2199931   3.06142775 -0.07026789  0.20966294]
 [ 1.30706537  2.18373408  0.70619482 -0.21398887]
 [-1.07471922 -0.34156791 -0.30165979 -0.62626162]
 [-0.79452106 -1.12769374  0.5356514   0.82808898]
 [ 0.53364938 -0.39252664 -0.89327254 -0.60239005]
 [-0.34979571  1.50331541  0.467521    0.12255861]
 [ 0.85094207 -0.24210178 -0.984189    0.54836486]]


In [8]:
# 布尔型索引
print(names=='Bob')
print(data[names=='Bob'])
print(names!='Bob')
print(data[~(names=='Bob')])# 使用~进行反转

[ True False False  True False False False]
[[-0.2199931   3.06142775 -0.07026789  0.20966294]
 [-0.79452106 -1.12769374  0.5356514   0.82808898]]
[False  True  True False  True  True  True]
[[ 1.30706537  2.18373408  0.70619482 -0.21398887]
 [-1.07471922 -0.34156791 -0.30165979 -0.62626162]
 [ 0.53364938 -0.39252664 -0.89327254 -0.60239005]
 [-0.34979571  1.50331541  0.467521    0.12255861]
 [ 0.85094207 -0.24210178 -0.984189    0.54836486]]


In [9]:
mask = (names=='Bob') | (names=='Will')
print(mask)
print(data[mask])

[ True False  True  True  True False False]
[[-0.2199931   3.06142775 -0.07026789  0.20966294]
 [-1.07471922 -0.34156791 -0.30165979 -0.62626162]
 [-0.79452106 -1.12769374  0.5356514   0.82808898]
 [ 0.53364938 -0.39252664 -0.89327254 -0.60239005]]


In [2]:
import  numpy as np

arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [4]:
arr = np.random.randn(6, 3)
print(arr)
print(np.dot(arr, arr.T))# 计算矩阵内积

[[-0.26783317 -0.01280273  0.18230101]
 [ 0.36741342 -1.60260926  0.78392119]
 [-0.82735806  0.00953338 -0.55083312]
 [ 0.21257818  1.41354988 -0.19956925]
 [ 1.12739284  1.30390088  1.23858616]
 [-0.69865366  0.06837629  1.11606121]]
[[ 0.10513218  0.0650219   0.12105445 -0.11141446 -0.09285118  0.38970631]
 [ 0.0650219   3.3178815  -0.7510705  -2.34371062 -0.70447042  0.50862883]
 [ 0.12105445 -0.7510705   0.98802937 -0.052473   -1.60258125 -0.03607489]
 [-0.11141446 -2.34371062 -0.052473    2.08314063  1.83560434 -0.27459672]
 [-0.09285118 -0.70447042 -1.60258125  1.83560434  4.5052678   0.68383673]
 [ 0.38970631  0.50862883 -0.03607489 -0.27459672  0.68383673  1.73838487]]


In [6]:
# 对于高维数组，transpose需要得到一个由编号组成的元组才能对这些轴进行转置
arr = np.arange(16).reshape((2, 2, 4))
print(arr)
print('----------------------------')
print(arr.transpose((1, 0, 2)))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
----------------------------
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [7]:
print(arr)
print('----------------------------')
print(arr.swapaxes(1, 2))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
----------------------------
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [9]:
arr = np.arange(10)

print(arr)
print(np.sqrt(arr))
print(np.exp(arr))

[0 1 2 3 4 5 6 7 8 9]
[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.        ]
[  1.00000000e+00   2.71828183e+00   7.38905610e+00   2.00855369e+01
   5.45981500e+01   1.48413159e+02   4.03428793e+02   1.09663316e+03
   2.98095799e+03   8.10308393e+03]


In [10]:
x = np.random.randn(8)
y = np.random.randn(8)

print(np.minimum(x, y))

[ 0.08971497  0.57169441 -0.16575108 -1.93084801 -0.89761078  0.30901905
  0.2393505  -0.10147055]


In [11]:
arr = np.random.randn(4, 4)
print(arr)
print(arr>0)
print(np.where(arr>0, 2, -2))

[[-1.09689645  2.21487853  0.0494108   0.17230215]
 [ 0.05167529 -2.10384902 -1.50898636  1.01575317]
 [ 2.79523206  0.57146598  1.93840667  0.09440613]
 [ 0.11831827  0.50731095  2.65976932 -0.72799341]]
[[False  True  True  True]
 [ True False False  True]
 [ True  True  True  True]
 [ True  True  True False]]
[[-2  2  2  2]
 [ 2 -2 -2  2]
 [ 2  2  2  2]
 [ 2  2  2 -2]]
