In [2]:
import numpy as np

world_alcohol = np.genfromtxt("world_alcohol.txt", delimiter=',', dtype=str, skip_header=1)# 读取txt文档
print(type(world_alcohol))
print(world_alcohol)

<class 'numpy.ndarray'>
[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ..., 
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [3]:
vector = np.array([1, 2, 3, 4])
matrix = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(vector)
print(matrix)

[1 2 3 4]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [4]:
print(vector.shape)
print(matrix.shape)
print(matrix.dtype)

(4,)
(3, 3)
int32


In [8]:
uruguay_other_1986 = world_alcohol[1, 4]# 通过索引查找数据
third_country = world_alcohol[2, 2]
print(uruguay_other_1986)
print(third_country)

0.5
Cte d'Ivoire


In [9]:
vector = np.array([5, 10, 15, 20])
print(vector[0:3])

[ 5 10 15]


In [13]:
matrix = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])
print(matrix[:, 1])
print(matrix[:, 0:2])

[10 25 40]
[[ 5 10]
 [20 25]
 [35 40]]


In [15]:
print(vector==10)
print(matrix==25)

[False  True False False]
[[False False False]
 [False  True False]
 [False False False]]


In [16]:
equal_to_ten = (vector == 10)# 通过boolean类型取值
print(vector[equal_to_ten])

[10]


In [18]:
second_column_25 = (matrix[:, 1]==25)
print(second_column_25)
print(matrix[second_column_25, :])

[False  True False]
[[20 25 30]]


In [20]:
equal_to_ten_and_five = (vector==10)&(vector==5)
equal_to_ten_or_five = (vector==10)|(vector==5)
print(equal_to_ten_and_five)
print(equal_to_ten_or_five)

[False False False False]
[ True  True False False]


In [25]:
vector = np.array(['1', '2', '3'])
print(vector.dtype)
print(vector)
vector = vector.astype(float)
print(vector.dtype)
print(vector)

<U1
['1' '2' '3']
float64
[ 1.  2.  3.]
