In [2]:
import numpy as np
B = np.arange(3)
print(B)
print(np.exp(B))#e的幂
print(np.sqrt(B))#开方

[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]


In [3]:
a = np.floor(10*np.random.random((3, 4)))
print(a)
print('--------')
print(a.ravel())# 转换为一维数组
print('--------')
a.shape = (6, 2)
print(a)
print('--------')
print(a.T)

[[ 6.  6.  1.  0.]
 [ 2.  0.  0.  2.]
 [ 9.  7.  2.  7.]]
--------
[ 6.  6.  1.  0.  2.  0.  0.  2.  9.  7.  2.  7.]
--------
[[ 6.  6.]
 [ 1.  0.]
 [ 2.  0.]
 [ 0.  2.]
 [ 9.  7.]
 [ 2.  7.]]
--------
[[ 6.  1.  2.  0.  9.  2.]
 [ 6.  0.  0.  2.  7.  7.]]


In [4]:
a = np.floor(10*np.random.random((2, 2)))
b = np.floor(10*np.random.random((2, 2)))
print(np.hstack((a, b)))# 横向叠加
print(np.vstack((a, b)))# 纵向叠加

[[ 9.  3.  9.  6.]
 [ 1.  2.  4.  9.]]
[[ 9.  3.]
 [ 1.  2.]
 [ 9.  6.]
 [ 4.  9.]]


In [5]:
a = np.floor(10*np.random.random((2, 12)))
print(np.hsplit(a, 3))# 横向切割
print(np.hsplit(a, (3, 4)))
a = np.floor(10*np.random.random((12, 2)))
print(np.vsplit(a, 3))

[array([[ 6.,  2.,  7.,  3.],
       [ 3.,  4.,  6.,  7.]]), array([[ 4.,  7.,  6.,  4.],
       [ 0.,  4.,  9.,  9.]]), array([[ 3.,  1.,  0.,  6.],
       [ 2.,  4.,  7.,  7.]])]
[array([[ 6.,  2.,  7.],
       [ 3.,  4.,  6.]]), array([[ 3.],
       [ 7.]]), array([[ 4.,  7.,  6.,  4.,  3.,  1.,  0.,  6.],
       [ 0.,  4.,  9.,  9.,  2.,  4.,  7.,  7.]])]
[array([[ 7.,  1.],
       [ 5.,  2.],
       [ 3.,  0.],
       [ 8.,  8.]]), array([[ 3.,  1.],
       [ 2.,  8.],
       [ 4.,  9.],
       [ 1.,  7.]]), array([[ 0.,  2.],
       [ 7.,  4.],
       [ 4.,  8.],
       [ 2.,  1.]])]


In [6]:
a = np.arange(12)
b = a
print(a)
print(b)
print(a is b)
b.shape = 3, 4
print(a.shape)
print(id(a))
print(id(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
True
(3, 4)
100958920
100958920


In [7]:
c = a.view()# 复制操作
print(c is a)
c.shape = 2, 6
c[0,4] = 1234
print(a)
print(id(a))# 值相同，地址不同
print(id(c))

False
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
100958920
100982600


In [9]:
d = a.copy()
d is a
d[0, 0] = 9999
print(d)# 值不相同，地址也不相同
print(a)

[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]


In [20]:
data = np.sin(np.arange(20)).reshape(5, 4)
print(data)
ind = data.argmax(axis=0)# 最大值的索引
print(ind)
data_max = data[ind, range(data.shape[1])]# 按照行，列查找值
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[ 0.98935825  0.84147098  0.99060736  0.6569866 ]


In [14]:
a = np.arange(0, 40, 10)
print(a)
b = np.tile(a, (4, 3))# 对ndarray进行扩展
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [24]:
a = np.array([[4, 3, 5], [1, 2, 1]])
print(a)
print('-------')
b = np.sort(a, axis=1)
print(b)
a.sort(axis=1)
print('-------')
print(a)
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
print('-------')
print(j)
print('-------')
print(a[j])

[[4 3 5]
 [1 2 1]]
-------
[[3 4 5]
 [1 1 2]]
-------
[[3 4 5]
 [1 1 2]]
-------
[2 3 1 0]
-------
[1 2 3 4]
