In [1]:
import numpy as np
print(np.arange(15))
a = np.arange(15).reshape(3, 5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
print(a.shape)
print(a.ndim)

(3, 5)
2


In [6]:
print(a.dtype)
print(a.dtype.name)
print(a.size)

int32
int32
15


In [7]:
np.zeros((3, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [10]:
np.ones((2, 3, 4), dtype=np.int32)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [13]:
np.random.random((2, 3))

array([[ 0.24261339,  0.68163395,  0.28385091],
       [ 0.34754847,  0.15220533,  0.60489473]])

In [14]:
from numpy import pi
np.linspace(0, 2*pi, 100)

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [15]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a-b)
print(b**2)
print(a<35)

[20 29 38 47]
[0 1 4 9]
[ True  True False False]


In [18]:
A = np.array([[1, 1],
              [0, 1]])
B =np.array([[2, 0],
             [3, 4]])
print(A*B)
print('---------')
print(A.dot(B))
print('---------')
print(np.dot(A, B))

[[2 0]
 [0 4]]
---------
[[5 4]
 [3 4]]
---------
[[5 4]
 [3 4]]
